services:
  frontend:
    tty: true
    build:
      context: .
      dockerfile: ./battleship-frontend/Dockerfile
    volumes:
      - ./battleship-frontend:/app
    ports:
      - 3000:3000
    networks:
      - battleship
  socket:
    tty: true
    build:
      context: .
      dockerfile: ./battleship-socket/Dockerfile
    volumes:
      - ./battleship-socket:/app
    ports:
      - 3002:3002
    networks:
      - battleship
  backend:
    tty: true
    build:
      context: .
      dockerfile: ./battleship-backend/Dockerfile
    ports:
      - 8080:8080
    networks:
      - battleship
networks:
  battleship:
